-- CreateTable
CREATE TABLE `PlatoOculto` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `plato` VARCHAR(191) NOT NULL,
    `creadoEn` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
